### ISSUE TITLE
RuntimeError: CUDA Setup failed despite GPU being available. 使用bitsandbytes0.39.0出错。

### ISSUE THREAD

**Issue by BaoyanWang** [yangjianxin1/Firefly#26]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/bitsandbytes-0.39.0-py3.8.egg/bitsandbytes/libbitsandbytes_cuda110.so
False
/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/bitsandbytes-0.39.0-py3.8.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: /workdir/common/miniconda3/envs/tmp_py38 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/bitsandbytes-0.39.0-py3.8.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: /workdir/common/miniconda3/envs/tmp_py38/lib/ did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/bitsandbytes-0.39.0-py3.8.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('443'), PosixPath('tcp'), PosixPath('//10.131.13.1')}
  warn(msg)
/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/bitsandbytes-0.39.0-py3.8.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('default'), PosixPath('/mnt/dolphinfs/hdd_pool/docker/share,default'), PosixPath('/mnt/dolphinfs/hdd_pool/docker/user/hadoop-health-alg,default'), PosixPath('/mnt/dolphinfs/ssd_pool/docker/share,default')}
  warn(msg)
/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/bitsandbytes-0.39.0-py3.8.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('-Djava.security.krb5.conf=/opt/meituan/hadoop/etc/hadoop/krb5.conf')}
  warn(msg)
/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/bitsandbytes-0.39.0-py3.8.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('http'), PosixPath('//config.hulk.vip.sankuai.com')}
  warn(msg)
/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/bitsandbytes-0.39.0-py3.8.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/contrib/capacity-scheduler/*.jar')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/bitsandbytes-0.39.0-py3.8.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 110
CUDA SETUP: Required library version not found: libbitsandbytes_cuda110.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=110 make cuda110
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "train_qlora.py", line 2, in <module>
    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
  File "/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/peft/__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/peft/mapping.py", line 16, in <module>
    from .peft_model import (
  File "/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/peft/peft_model.py", line 34, in <module>
    from .tuners import (
  File "/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/peft/tuners/__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/peft/tuners/lora.py", line 41, in <module>
    import bitsandbytes as bnb
  File "/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/bitsandbytes-0.39.0-py3.8.egg/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/bitsandbytes-0.39.0-py3.8.egg/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/bitsandbytes-0.39.0-py3.8.egg/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/bitsandbytes-0.39.0-py3.8.egg/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/bitsandbytes-0.39.0-py3.8.egg/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/workdir/common/miniconda3/envs/tmp_py38/lib/python3.8/site-packages/bitsandbytes-0.39.0-py3.8.egg/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by BaoyanWang** [comment]
cuda 版本11.0,看有人说升级到11.8就好了，想咨询一下您的cuda版本

**Comment by sunbeibei-hub** [comment]
遇到相同的问题，楼主解决了吗

**Comment by BaoyanWang** [comment]
使用下面步骤手动安装：
pip uninstall bitsandbytes --yes # if you already installed it with pip
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=114 make cuda11x GPP=$(which g++) -j 2
pip install .
python check_bnb_install.py
python -c 'import bitsandbytes'

**Comment by BaoyanWang** [comment]
手动安装解决
