### ISSUE TITLE
使用train_qlora.py时报错：arrow::fs::FinalizeS3 was not called even though S3 was initialized.

### ISSUE THREAD

**Issue by CnDouglasYoung** [yangjianxin1/Firefly#50]
目前使用全参数训练正常，使用qlora时会报错。完整报错为：
verify trainable params the model
torch.float32 143130624 1.0
torch.float32 143130624
2023-07-05 23:33:31.639 | INFO     | component.dataset:__init__:14 - Loading data: ./data/dummy_data.jsonl
2023-07-05 23:33:31.645 | INFO     | component.dataset:__init__:17 - there are 33 data in dataset
2023-07-05 23:33:31.652 | INFO     | __main__:main:183 - *** starting training ***
  0%|                                                                                             | 0/2 [00:00<?, ?it/s]`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
Error invalid device ordinal at line 359 in file /home/tim/git/bitsandbytes/csrc/pythonInterface.c
/arrow/cpp/src/arrow/filesystem/s3fs.cc:2598:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit

这个报错能搜到的解决办法都不太明确，实在搞不定，发个issue请教一下

使用模型：YeungNLP/firefly-baichuan-7b-qlora-sft-merge
使用显卡：4090
使用系统：windows wsl下的Ubuntu 22.04.2 LTS
加载训练数据没有动，还是./data/dummy_data.jsonl

环境包已经按requirements.txt做了更新，具体如下：
Package                  Version
------------------------ -------------
absl-py                  1.4.0
accelerate               0.21.0.dev0
aiofiles                 23.1.0
aiohttp                  3.8.4
aiosignal                1.3.1
altair                   5.0.0
anyio                    3.6.2
async-timeout            4.0.2
attrs                    23.1.0
bitsandbytes             0.39.0
blinker                  1.4
cachetools               5.3.1
certifi                  2023.5.7
charset-normalizer       3.1.0
click                    8.1.3
cmake                    3.26.3
command-not-found        0.3
contourpy                1.0.7
cpm-kernels              1.0.11
cryptography             3.4.8
cycler                   0.11.0
datasets                 2.12.0
dbus-python              1.2.18
deepspeed                0.9.5
dill                     0.3.6
distro                   1.7.0
distro-info              1.1build1
evaluate                 0.4.0
fastapi                  0.95.1
ffmpy                    0.3.0
filelock                 3.12.0
fonttools                4.39.4
frozenlist               1.3.3
fsspec                   2023.5.0
google-auth              2.21.0
google-auth-oauthlib     1.0.0
gradio                   3.30.0
gradio_client            0.2.4
grpcio                   1.56.0
h11                      0.14.0
hjson                    3.1.0
httpcore                 0.17.0
httplib2                 0.20.2
httpx                    0.24.0
huggingface-hub          0.14.1
icetk                    0.0.7
idna                     3.4
importlib-metadata       4.6.4
jeepney                  0.7.1
Jinja2                   3.1.2
joblib                   1.3.1
jsonschema               4.17.3
keyring                  23.5.0
kiwisolver               1.4.4
latex2mathml             3.75.5
launchpadlib             1.10.16
lazr.restfulclient       0.14.4
lazr.uri                 1.0.6
linkify-it-py            2.0.2
lit                      16.0.3
loguru                   0.7.0
Markdown                 3.4.3
markdown-it-py           2.2.0
MarkupSafe               2.1.2
matplotlib               3.7.1
mdit-py-plugins          0.3.3
mdtex2html               1.2.0
mdurl                    0.1.2
more-itertools           8.10.0
mpi4py                   3.1.4
mpmath                   1.3.0
multidict                6.0.4
multiprocess             0.70.14
netifaces                0.11.0
networkx                 3.1
ninja                    1.11.1
numpy                    1.21.4
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
oauthlib                 3.2.0
orjson                   3.8.12
packaging                23.1
pandas                   1.2.5
peft                     0.4.0.dev0
Pillow                   9.5.0
pip                      23.1.2
protobuf                 4.23.3
psutil                   5.9.5
py-cpuinfo               9.0.0
pyarrow                  12.0.0
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pydantic                 1.10.7
pydub                    0.25.1
Pygments                 2.15.1
PyGObject                3.42.1
PyJWT                    2.3.0
pyparsing                2.4.7
pyrsistent               0.19.3
python-apt               2.4.0+ubuntu1
python-dateutil          2.8.2
python-multipart         0.0.6
pytz                     2023.3
PyYAML                   5.4.1
regex                    2023.5.5
requests                 2.30.0
requests-oauthlib        1.3.1
responses                0.18.0
rsa                      4.9
safetensors              0.3.1
scikit-learn             1.3.0
scipy                    1.10.1
screen-resolution-extra  0.0.0
SecretStorage            3.3.1
semantic-version         2.10.0
sentencepiece            0.1.99
setuptools               68.0.0
six                      1.16.0
sniffio                  1.3.0
starlette                0.26.1
sympy                    1.11.1
systemd-python           234
tensorboard              2.13.0
tensorboard-data-server  0.7.1
tensorboardX             2.6.1
threadpoolctl            3.1.0
tokenizers               0.13.3
toolz                    0.12.0
torch                    1.13.0
torchsummary             1.5.1
torchvision              0.15.2
tqdm                     4.62.3
transformers             4.31.0.dev0
triton                   2.0.0
typing_extensions        4.5.0
tzdata                   2023.3
ubuntu-advantage-tools   8001
uc-micro-py              1.0.2
ufw                      0.36.1
unattended-upgrades      0.1
urllib3                  1.26.16
uvicorn                  0.22.0
wadllib                  1.3.6
websockets               11.0.3
Werkzeug                 2.3.6
wheel                    0.37.1
xkit                     0.0.0
xxhash                   3.2.0
yarl                     1.9.2
zipp                     1.0.0

**Comment by CnDouglasYoung** [comment]
在此之前遇到了 AttributeError: /home/douglas/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cquantize_blockwise_fp16_nf4 的问题
按照 https://github.com/artidoro/qlora/issues/31#issuecomment-1582238190 的做法处理了下，确实没那个报错了，然后出现了上述的问题

**Comment by VelvetAcidChrist** [comment]
A simple solution to fix this error:

`pip install --upgrade --force-reinstall pyarrow==11.0.0`

**Comment by CnDouglasYoung** [comment]
> A simple solution to fix this error:
> 
> `pip install --upgrade --force-reinstall pyarrow==11.0.0`

Thanks for your help, it did solve the error above, and then a new one appeared
多谢你的帮助，它确实解决了上面那个报错，然后又出现了新的一个

From the following URL, it seems that bitsandbytes does not support WSL2. Later I plan to do a dual system to deal with this problem, hope it works
从下面这个url看，应该是bitsandbytes不支持wsl2导致的。稍后我打算做一个双系统来处理这个问题，希望能管用

https://github.com/TimDettmers/bitsandbytes/issues/470#issuecomment-1618206509

**Comment by CnDouglasYoung** [comment]
用ubuntu 22.04成功跑通了。
有两个发现：
1、cuda里自带的驱动安装包挺好用的，如果手动装不好，可以试试让cuda帮你装
2、cuda在下载时有个 WSL_Ubuntu 的选项，有可能之前我没注意到这个，在WSL里直接用了Ubuntu的，导致了上面一系列问题。有相似问题的朋友，可以先试下WSL_Ubuntu的cuda，不行再换系统

**Comment by zhangjunyi111** [comment]
@CnDouglasYoung 什么是cuda里自带的驱动安装包
